### ISSUE TITLE
Add mesh_ifname similar to lan_ifname 

### ISSUE THREAD

**Issue by tobox** [freifunk-gluon/gluon#1206]
For offloaders, it is common to provide both client lan and mesh. This can easily be achived by setting the correct interface names (be it additional USB nics or VLANs) using uci. 

If only client lan or mesh is used, updating /lib/gluon/core/sysconfig/lan_ifname also makes the setup safe for firmware updates.

But if both client lan and mesh are used, both interfaces are silently bridged during updates, resulting in strange behaviour.

**Comment by NeoRaider** [comment]
lan_ifname and wan_ifname are storing the OpenWrt/LEDE LAN/WAN port names; any manual adjustment to these files is a hack and not supported officially (they will go away eventually, as LEDE's /etc/board.json contains the same information).

Additional mesh interfaces should be added as new UCI sections in /etc/config/network instead of changing existing ones; such sections will not be touched on upgrades.
