### ISSUE TITLE
Limit the number of clients on each model accordingly

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#125]
On OpenWrt, there’s a “common option” `maxassoc` that should be set to a reasonable number (between 10 and 30 depending on the model), so the routers don't get overwhelmed when too many clients try to connect to the same router at once.

see discussion here: http://superuser.com/questions/774877/stop-users-from-connecting-if-a-wifi-is-full?noredirect=1#comment1007154_774877

**Comment by RubenKelevra** [comment]
I asked nbd two years ago, about limiting a router to 60 with maxassoc, he said that we shouldn't do this. Since the wifi-driver do it's best to serve data to all clients which are connected. Since not all clients make traffic, you might limit a box to only clients which does not really need a wifi. Exclude some other users which might try to connect.

We saw more than 100 clients on a Nanostation M2 which got only 400 MHz / 32 MB RAM working nicely.

**Comment by NeoRaider** [comment]
Closing, as this is an issue impossible to solve. In most common scenarios, most associated stations are idle most of the time, so there es no way to limit their number in a sane way.
