### ISSUE TITLE
WAN Uplink via private WLAN

### ISSUE THREAD

**Issue by AbsoluterBeginner** [freifunk-gluon/gluon#140]
Instead of connecting my freifunk AP via LAN I would like it to connect it to my private Wireless Network for Uplink. Is this possible?

**Comment by hackrid** [comment]
could you please provide a complete set of commands to get a uplink via wlan working?
best regards

**Comment by tcatm** [comment]
@hackrid I think you should consult the mailinglist or the freifunk forum. This issue tracker is for development of gluon only.

**Comment by g3ntleman** [comment]
I have use for a WWAN uplink as well in several places, but I agree that one should not use the internal WLAN interface of the node for the uplink. Instead, I want to attach a WLAN USB stick for that purpose.

Of cause, I need drivers for that hardware. Any idea why gluon nodes cannot out-of-the-box resolve DNS addresses (and thus use opkg) to install new software? Sounds like there is something broken to me...

**Comment by NeoRaider** [comment]
@g3ntleman, this is probably an issue of your community's network setup: http://gluon.readthedocs.org/en/latest/user/faq.html#dns-does-not-work-on-the-nodes

Additional WLAN interfaces can't be supported at the moment (we first need to restructure our network config, OpenWrt generally doesn't handle USB WLAN very well...). Using a second Gluon node for uplink is really the best option.

**Comment by thomaszbz** [comment]
@NeoRaider I still think this is a relevant and valid feature request. Even if this is not to be solved at the moment, maybe this could be done later. This issue could just stay open for that purpose.

This feature request is relevant _especially_ for freifunk because many users need to place their FF routers at windows, balconies and so forth. Which also makes it _valuable_ for freifunk as it allows better and more flexible positioning of nodes.

I think that bandwidth is _not_ an issue here in the first place, at least in common cases: 16 Mbit twice is inefficient but eventually makes it through a good 802.11n connection. 4, 8 or 16 Mbit would be perfectly fine and beneficial for freifunk. Leave alone that at least my node _never_ exceeds 8 Mbit of bandwidth although 16 Mbit are available.

I think this feature is also as valuable as the private wifi feature. But in contrast to the private wifi feature, this issue is beneficial for freifunk (we talk about the uplink of a _freifunk_ node here).

Personally, I don't care a lot if a separate wifi dongle is used (which even allows another channel) or if the existing radio of the freifunk node is used (on FF's channel). I think both setups make sense, it depends on user's preference.

Having configuration for existing radios in an always-working setup would be elegant whereas usb wifi dongles need additional drivers which in itself comes along with a lot of trouble (=> maybe only support a few devices).

**Comment by g3ntleman** [comment]
I could not agree more. I tried to establish a configuration for a certain WLAN USB Dongle once and failed. It seemed to connect, but I failed to adapt the firewall rules correctly (I'm not an admin).

**Comment by thomaszbz** [comment]
Maybe a hardware-based workaround for ~20 EUR (did not test it myself):
http://en.vonets.es/products/VAP11G-300/

The device's bridge functionality is pretty much what we need in software.

**Comment by songshura** [comment]
for my personal use case i am looking for this functionality, as pretty much described by  @thomaszbz ..
minimal cost not having to use 2 routers, minimal setup hassle running cables and maximum range for the buck by placing them behind the window facing the street.

As i need to setup a bunch of these (hopefully more) i do not mind building the firmware myself, adding the drivers and some setup scripts.... .

the preferred method i guess would be adding a usb wifi adapter like for instance https://www.amazon.de/LogiLink-WL0084E-Wireless-LAN-Nano-Adapter-150Mbps/dp/B007JWB1N2
attached to for a gl-ar150 as example.

as this is an old discussion, does anybody have any experience with such a setup or some general recommendation for the hardware used

**Comment by Adorfer** [comment]
the general recommendation is already above: use a second (MIMO) router, as APclient. on openwrt/Lede. 
nothing else. if you like to go with cheap or expensive wifi sticks: good luck. never heard it working satisfying.

**Comment by songshura** [comment]
@Adorfer thanks for the reply....
there are not that many reviews to go by... hence my question, seen a few successful setups, several raspberry pi's.....  but these do not report on long term stability..

in your experience, are the wifi sticks just crap hardware wise, or are the drivers in openwrt just buggy???

**Comment by Adorfer** [comment]
**I do not have any idea how to make something more reliable, efficient and affordable than an 841er (or Nanostation of whatever model you like) as an AP client.** 

Off course you may put an RPI with a wifi stick or any "special solution" like the VPA11G. 
But it's expensive, non performant, unreliable and takes a lot of work to set it up plus to keep it running for multiple years. 
Perhaps you can sort out 2-3 of the 5-6 points, but it will certainly not reduce cost or work, but make it worse. 
it's a free country. But the fact that i do not know of any of those setups running successful for more than a few weeks or months: there might be a reason. Or those people were just lazy/incompetent or whatever that they stopped/modified their setup. You have to ask them. the list of those proposing such solutions and even showing initial setups is long. Perhaps you get a more reasoning statement than my assumptions.
