### ISSUE TITLE
Monitor Nodes via SNMP

### ISSUE THREAD

**Issue by klausdint** [freifunk-gluon/gluon#1497]
Is it possible to monitor Nodes via SNMP protocol? If not, can you add this feature in addition with some basic settings like community name, enable/disable, etc?

**Comment by Adorfer** [comment]
basically it's possible, but not feasable due to flash size constraints von >90% of the existing plastic routers. 
In plus, if you want to change configs, you have to secure the snmp traffic, leaving the need for some implementation of SSL, which is -same reason as above- not available for the moment. 

have a look at this old discussion: 
https://forum.freifunk.net/t/ff-router-per-snmp-monitoren/637

**Comment by rotanid** [comment]
as already described this would need a good amount of flash space and work, maybe it would be possible via a package which can only be installed on nodes with a big flash chip...
overall, we decided to reject this issue as no one of the current team has the time to even make a feasibility study - let alone the implementation.
