### ISSUE TITLE
Derive target domain from location

### ISSUE THREAD

**Issue by mweinelt** [freifunk-gluon/gluon#1527]
This probably needs to extend domains (and pretty names) with polygons so locations can be automatically selected based on the position.

**Comment by 2tata** [comment]
This will be already provided by #1393

**Comment by rotanid** [comment]
yes, should be handled by that PR, review still pending:(

**Comment by kpanic23** [comment]
@mweinelt 
Have a look at https://github.com/ff3l/packages
I've extended FFRGB's gluon-segment-mover to have this feature. The package gluon-config-mode-segment-mover can be used to be able to disable it in config mode.
It uses a web API to get the correct domain for the coordinates, since our geojson shape files would be larger than most devices' flash chips. The (super simple) web API can be found at https://github.com/ff3l/ff3l-api

**Comment by 2tata** [comment]
Shall we close this Issue due to its duplicated ? by the hoodselector PRs ?

**Comment by rotanid** [comment]
@2tata an issue can be solved by a merged PR. therefore it stays open until the solution is merged :)

**Comment by CodeFetch** [comment]
@rotanid Can be closed now. The suggestion by kpanic23 has been incorporated in #1773.

**Comment by 2tata** [comment]
solved by #1739

**Comment by CodeFetch** [comment]
@rotanid Please close this issue.
