### ISSUE TITLE
Allow to choose fastd without encryption via expert mode

### ISSUE THREAD

**Issue by ohrensessel** [freifunk-gluon/gluon#172]
For some installations it might be appropriate to use null+salsa2012+gmac as fastd method (authenticated-only) instead of the recommended salsa2012+gmac because of performance reasons.

An option within the expert mode would be helpful while clearly stating that this has (or might have) some implications in regard to the Störerhaftung, as traffic can be easily read along by a third party.

A community might decide to offer null+salsa2012+gmac on all or some of its gateways. Maybe such an expert mode option should be shown if there is more than one method defined in the site.conf. First method should then be the default one.

What do you think?

**Comment by NeoRaider** [comment]
Okay, so my current plan for this issue is the following:

* The community can decide to allow using the `null` method. This is configured on the fastd servers and a flag is set in the `site.conf`.
* If the `site.conf` flag signals that the community allows `null`, the expert mode will allow to choose between "security" and "performance" settings for the mesh VPN
* A community which uses "security" mode by default (which should be most) would just set the non-null methods in the `methods` field on the `site.conf`
* A community which uses "performance" mode by default can set the `methods` field to all supported methods (`null` and a secure method), with `null` as the first entry so that it is preferred
* A community can choose not to allow any methods but `null` by setting the method list to just `null` (not recommended!)
* The option in the expert mode will prepend the value `null` to the list of configured methods, or remove it from this list

This will allow communities to default to
* Only allow secure methods
* Default to secure methods, but allow `null`
* Default to `null`, but allow secure methods
* Only allow `null`

The user can always choose to use secure mode unless the community doesn't allow any methods but `null`. When secure mode is chosen, the value `null` is completely removed from the list of supported methods in the fastd configuration, so only secure methods are used.

And now I'd like to have some feedback...

**Comment by T-X** [comment]
Technically looks good. Should enable every community to configure their prefered policy. And it nevertheless keeps the config mode simple for the user. I like that :).

On the "political" side I don't like this feature. I'm a little scared that this could leverage ISPs to go against net neutrality. They'll look at the traffic and might start pointing their fingers at Freifunk and will urge the politicians to drop their support for net neutrality.
