### ISSUE TITLE
introduce build flag GLUON_LEGACY

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/gluon#1737]
flag a target as legacy, requiring firmware builders to decide whether to build only sysupgrade or sysupgrade and factory images

GLUON_LEGACY={false,true,sysupgrade}

**Comment by NeoRaider** [comment]
While I don't have a strong opinion on this (and will hopefully not turn this issue into a bikeshedding discussion), I think I'll go with the following values for GLUON_LEGACY:
- `0`: don't build any legacy images
- `1`: build legacy sysupgrade images
- `full`: build legacy sysupgrade and factory images

This has two advantages in my opinion:
- 0/1 is already used for other options
- having a separate value for the "sysupgrade+factory" setting rather than for the "sysupgrade only" setting makes this option special, hopefully hinting site builders at not choosing this option ;)
