### ISSUE TITLE
batman-adv-15 requires a larger MTU

### ISSUE THREAD

**Issue by tcatm** [freifunk-gluon/gluon#275]
batman-adv-15 requires a larger MTU (1532) on the wireless interface. To avoid fragmentation, Gluon should adjust interfaces accordingly.

**Comment by FreifunkUFO** [comment]
Would be nice to adjust that value via site.conf. just as https://github.com/freifunk-leipzig/gluon-packages/commit/a2da53405493c75aade4b1a70c958c57fb1d3ec4

otherwise, mtu could also be calculated by a script, which collects several settings from firmware/batmanadv and used features. but that lacks transparency for community admins. so i would still prefer a site-conf parameter

**Comment by NeoRaider** [comment]
Fixed by freifunk-gluon/packages@eca1bac23f6c943c71d2eabe352c7032e3617245
