### ISSUE TITLE
Make statuspage available to all ip

### ISSUE THREAD

**Issue by A-Kasper** [freifunk-gluon/gluon#645]
It would be nice if the statuspage would work on every ip of the device. especially the next-neighbour address would be a nice feature to see whats going on on the used router...

**Comment by NeoRaider** [comment]
It does. I've just tested again, the status page is working fine here on the next-node address (the status page is one of the principal usecases of the next-node address after all).

Please note that you still need to be able to reach the actual, unique IPv6 address of the node for the status page to be able to load its data (this could be fixed in the future though).
