### ISSUE TITLE
Add support for Rocket M5 XW

### ISSUE THREAD

**Issue by aipfel** [freifunk-gluon/gluon#722]
It would be nice to have support for this in our next Version
OpenWRT has allready support for it:
https://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/openwrt-15.05.1-ar71xx-generic-ubnt-rocket-m-xw-squashfs-factory.bin

The difference to the normal version is the LAN-Port patch, but has already been fixed at May 2015:
https://patchwork.ozlabs.org/patch/461730/

**Comment by NeoRaider** [comment]
Support added in 5bfb06fe36348305e91cdf975c0d9d97d8cd14a2 (marked as BROKEN). Please test.

**Comment by aipfel** [comment]
Okay, i tested them today and AirOS says: 'firmware check failt'. So i tried to flash OpenWRT itself but the firmware check fails too. CC 15.05 can be installed and works fine! The LAN-Port does his job aswell. What is the difference of
openwrt-15.05-ar71xx-generic-ubnt-rocket-m-xw-squashfs-factory.bin
and
openwrt-15.05.1-ar71xx-generic-ubnt-rocket-m-xw-squashfs-sysupgrade.bin
The first is working, the last doesn't ?!?

After all, i tried to install the Firmware over SSH on openwrt with -F (force) but then the rocket is broken.
Any Ideas?

by the way: original AirOS shows the same symptoms:
XM.v5.5.11.28002.150723.1344.bin 'firmware check fail'
XM.v5.5.10.24238.141001.1641.bin works

If I should try something, let me know!

**Comment by NeoRaider** [comment]
@aipfel, "The first one is working, the last doesn't": If you didn't mistype, the first one is a factory image, and the second one is a sysupgrade one.

"Firmware check fail" sounds a lot like you broke u-boot's flash layout definition, which happens when an OpenWrt image with broken flash layout (with is true for 15.05.1 and everything older) is installed from certain versions of AirOS. I'm not sure if it is possible to recover from this state without a serial console, broken flash layouts are annoying...

One note: On Ubiquiti devices, it is very important to differentiate between factory and sysupgrade images. factory images are used to flash from AirOS and u-boot recovery, sysupgrade from everything OpenWrt-based.

Needing -F probably means that you tried to flash a factory image (a sysupgrade image would not need -F), in which case a bricked device is entirely expected.

**Comment by aipfel** [comment]
Sorry, this was a mistype. Both were factory.

Okay, now i did the following: I updated the Rocket to 5.6.4 with the new u-boot 1.1.4-s958 and then i was able to flash CC 15.05.1, but no Gluon: Firmware check failt 

With tftp, i was able to flash the rocket back to AirOS. That's not the Problem

Do I have proceed as follows: AirOS 5.5.8 --> AirOS 5.6.4 --> CC 15.05.1 --> Gluon sysupgrade ?

**Comment by NeoRaider** [comment]
@aipfel, if you don't plan to ever go back to AirOS, that's a possible way to proceed. Your flash layout definition in U-boot is probably broken, but as OpenWrt/Gluon don't care, everything should work fine.

**Comment by aipfel** [comment]
okay, i try it later...

Do you stay at WCW?

**Comment by NeoRaider** [comment]
Yes, I'll attend WCW.

**Comment by aipfel** [comment]
okay, then I'll bring the device with me

**Comment by aipfel** [comment]
"Do I have proceed as follows: AirOS 5.5.8 --> AirOS 5.6.4 --> CC 15.05.1 --> Gluon sysupgrade ?"

I test it but CC15.05.1 don't updating the rocket 
After 'upgrading' to Gluon via UI, he starts again with CC 15.05.1

Exist a way to skip the firmwarecheck from u-boot?

**Comment by NeoRaider** [comment]
@aipfel, ah, of course. U-boot from AirOS 5.6.x doesn't unlock the flash, so OpenWrt CC will end up with unwriteable flash.

If you have a serial console, you should be able to flash a Gluon factory image via the "urescue" command after resetting the MTD layout (the command is something like "mtdparts default", you can find out using the "help" command.) Resetting the MTD layout is not permanent, but it is enough to make U-boot accept an image with the correct flash layout...
